Add with_grant_option to postgresql_default_privileges
cyrilgdn/terraform-provider-postgresql pull request #10
Opened 2020-12-02 17:30 UTC by stawii

This option exists in `postgresql_grant` but was missing in `postgresql_default_privileges`.
It is required to setup many things including Vault PostgreSQL Database Secrets Engine.

2020-12-12 19:04 UTC, cyrilgdn requested changes
@stawii Thanks for the patch :+1: 

Could you add this new field in one of the test so it asserts that the SQL is valid please?

2021-01-08 12:20 UTC, stawii commented
Sorry for late reply. There is no test in `resource_postgresql_grant` that I can take as an example.
I guess adding those tests might be another issue and out of scope of this PR ;)

2021-01-08 14:31 UTC, cyrilgdn commented
@stawii You can simply add the flag (to true) in [this test](https://github.com/cyrilgdn/terraform-provider-postgresql/blob/master/postgresql/resource_postgresql_default_privileges_test.go#L29-L36) and check the attribute [here](https://github.com/cyrilgdn/terraform-provider-postgresql/blob/master/postgresql/resource_postgresql_default_privileges_test.go#L58-L60), even if will not assert that use has the grant option, it'll cover the code and assert the query is valid.

2021-03-12 10:22 UTC, cyrilgdn approved these changes
I'll add the test.

2021-03-12 10:22 UTC, merged