Add Postgresql Publication Resource
cyrilgdn/terraform-provider-postgresql pull request #192
Opened 2022-03-13 18:54 UTC by chromko

This PR adds the new resource postgresql_publication for managing PostgreSQL publications.
# Example
```
resource "postgresql_publication" "test" {
	name     = "publication"
	database = "test_db"
	owner = "postgres"
	all_tables = true
}
```

2022-03-15 07:18 UTC, chromko commented
@cyrilgdn Hello! 
please let me know what do you think about it.

2022-04-16 17:01 UTC, cyrilgdn commented
For the failing golangci-lint test, you just have to merge master and it will fix it.

2022-04-18 10:38 UTC, chromko commented
> For the failing golangci-lint test, you just have to merge master and it will fix it.

Thanks. Merged

2022-05-04 08:41 UTC, chromko commented
Hello! Any updates?

2022-05-05 18:05 UTC, cyrilgdn requested changes
Thanks for this huge work :+1: 

As I've never use publications, I'll trust you and the tests to assert that it works.
Here are a couple of comment, I still need to read the test (this is a big review :smile: )

2022-05-05 18:06 UTC, cyrilgdn commented
Also there's a couple of lint warnings in Golangci-lint

2022-05-07 19:48 UTC, chromko commented on postgresql/resource_postgresql_publication.go
> +)
I'd prefer to use constant. It allows to avoid simple and annoying mistakes for me.

2022-05-07 21:03 UTC, chromko commented on postgresql/resource_postgresql_publication.go
> +				tlist = append(tlist, t.(string))
No, here we can't use pq.QuoteIdentifier here.
Tables cannot be quoted here https://www.postgresql.org/docs/current/sql-createpublication.html . 
Pq returns error for applying this.

2022-05-07 21:25 UTC, chromko commented on postgresql/resource_postgresql_publication.go
> +			return tablesString, fmt.Errorf("attribute `%s` cannot be used when `%s` is true", pubTablesAttr, pubAllTablesAttr)
Thx, used it

2022-05-07 21:25 UTC, chromko commented on postgresql/resource_postgresql_publication.go
> +	PublicationName := d.Get(pubNameAttr).(string)
fixed

2022-05-07 21:26 UTC, chromko commented on postgresql/resource_postgresql_publication.go
> +	// attrs = append(attrs, fmt.Sprintf("publish = '%s'", strings.Join(attrs, ", ")))
fixed

2022-05-07 21:26 UTC, chromko commented on postgresql/resource_postgresql_publication.go
> +	param_alter_template := "ALTER PUBLICATION %s %s"
Fixed

2022-05-07 21:27 UTC, chromko commented on postgresql/resource_postgresql_publication.go
> +	}
Thanks, used it

2022-05-07 21:27 UTC, chromko commented on postgresql/resource_postgresql_publication.go
> +	}
Used it, Thanks

2022-05-07 21:27 UTC, chromko commented on postgresql/resource_postgresql_publication.go
> +			return err
Used it, Thanks

2022-05-07 21:27 UTC, chromko commented on postgresql/resource_postgresql_publication.go
> +	fmt.Fprint(b, name, " ", tables, " ", publicationParameters)
Used it, Thanks

2022-05-08 14:18 UTC, cyrilgdn approved these changes
Many thanks  :clap: :+1:

2022-05-08 14:19 UTC, merged

2022-05-08 14:55 UTC, cyrilgdn commented
FYI, this has just been released in [v1.16.0](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest)