Order publication tables
cyrilgdn/terraform-provider-postgresql pull request #219
Opened 2022-06-01 11:53 UTC by nguyenhoaibao

Fixes https://github.com/cyrilgdn/terraform-provider-postgresql/issues/218

2022-06-17 08:41 UTC, cyrilgdn requested changes
Hi @nguyenhoaibao ,

Thanks for your PR.

This fix works only if you sorted the table in the TF definition.
I think that the right fix would be to switch `tables` from `TypeList` to `TypeSet` which is actually an unordered array.

Would you want to give it a try?

I think we just need to change the type, then cast with `tables.(*schema.Set)` instead of `tables.([]interface{})` and when needed (to `range` over the list for example), we can call the `tables.(*schema.Set).List()` function of Set to get an array.

Also it would be great to tweak the tests so they fail without the fix.

2022-06-20 02:44 UTC, nguyenhoaibao commented
@cyrilgdn thanks for your reviewing. Let me try with your suggestion.

2022-06-22 10:08 UTC, nguyenhoaibao commented
@cyrilgdn I made a change using your suggestion. Please take a look.

2022-06-22 10:42 UTC, nguyenhoaibao commented on postgresql/resource_postgresql_publication.go
> -	switch {
I see these error handling are redundant so I removed as well.

2022-06-22 11:45 UTC, nguyenhoaibao commented on postgresql/resource_postgresql_publication.go
> -		return fmt.Errorf("Error reading Publication tables: %w", err)
I see these error handling are redundant so I removed as well.

2022-06-22 15:03 UTC, nguyenhoaibao commented on postgresql/resource_postgresql_publication.go
> +	if err := rows.Err(); err != nil {
I added this error handling here to catch any error that can happen during the rows.Next iteration, as described in the  doc https://pkg.go.dev/database/sql#Rows.Err

2022-07-20 20:02 UTC, cyrilgdn approved these changes
Thanks :+1:

2022-07-20 20:03 UTC, merged