Add security label resource
cyrilgdn/terraform-provider-postgresql pull request #365
Opened 2023-10-18 17:22 UTC by jbunting

I've added a security label resource. This allows to create and manage security labels in postgres (https://www.postgresql.org/docs/current/sql-security-label.html).

Unfortunately, in order to test the security label operations, a "security label provider" has to be installed. My first commit in this PR does that, but to be honest its a bit onerous and it copies a little bit of code from postgres's test tree. I'm fully open to thoughts on how to better handle that part.

I believe this also addresses #276 .

2024-04-18 12:18 UTC, Teabeats commented
@jbunting Can you bring in https://github.com/jbunting/terraform-provider-postgresql/pull/1 into this PR to add a doc page for this resource?

2024-04-24 08:52 UTC, Teabeats approved these changes
Verified working e2e with this temporary release: https://registry.terraform.io/providers/Teabeats/postgresql/latest/docs/resources/postgresql_security_label

2024-05-07 13:54 UTC, jarpoole reviewed
Thank you for contributing @jbunting!

2024-05-07 13:54 UTC, jarpoole commented on postgresql/resource_postgresql_security_label.go
> +			StateContext: schema.ImportStatePassthroughContext,
Not well versed in writing Terraform providers but does this mean the resource supports importing? I personally feel importing is quite important to help with adoption and so it this is the case I think it makes sense to add an import example similar to a lot of the other resources? 

![image](https://github.com/cyrilgdn/terraform-provider-postgresql/assets/43940867/f7da1ba0-fddd-4785-baf9-874fb6b43e62)

Or even simpler: 
![image](https://github.com/cyrilgdn/terraform-provider-postgresql/assets/43940867/4c6f0259-7839-4659-afe5-e2801087143f)

2024-07-03 23:46 UTC, glangho commented
Would be great to have this officially.

> Verified working e2e with this temporary release: https://registry.terraform.io/providers/Teabeats/postgresql/latest/docs/resources/postgresql_security_label

Appreciate the effort but this just times out on me. Connecting as an entra app reg admin.  Not sure if there's a way to debug.  Other resources deploy fine.  Hoping we get an official cut soon

2024-07-11 18:37 UTC, glangho commented
Periods ('.') and at ('@') symbols (i.e., users in entra) also have the same problems as dashes so john.doe@postgresql.com gets saved in the security labels table as "john.doe@postgresql.com", again failing to match after the apply takes place.

2024-08-19 11:58 UTC, DzmtrShlh commented
Hello everyone!

Can confirm that I ran into the same issue as @glangho when I was testing postgresql_security_label resource. Should mention that resource was created (group in my case) and I was able to login as a member of this group.

Also interested in Microsoft Entra authentication for Azure Database for PostgreSQL - Flexible Server that requires postgresql_security_label resource to be introduced in official release.

2024-10-15 10:29 UTC, martindz commented on postgresql/resource_postgresql_security_label.go
https://github.com/cyrilgdn/terraform-provider-postgresql/blob/63519b7aa4c4f5e1ab5b9963054f080f84023cb1/postgresql/resource_postgresql_security_label.go#L69
few lines contain quoteliteral, which might cause the issue with quotes reported before. Could you please try to fix it before approval? Thanks

2024-10-15 10:32 UTC, martindz commented on postgresql/resource_postgresql_security_label.go
> +	if err := resourcePostgreSQLSecurityLabelUpdateImpl(db, d, pq.QuoteLiteral(label)); err != nil {
few lines contain quoteliteral(label), what might cause the issue with quotes in the label Objname reported before. Could you please try to make it work - to create objname/label without quotes in postgresql?

2024-10-16 13:07 UTC, martindz commented on postgresql/resource_postgresql_security_label.go
> +	if err := resourcePostgreSQLSecurityLabelUpdateImpl(db, d, pq.QuoteLiteral(label)); err != nil {
query := "SELECT objtype, objname, provider, label FROM pg_seclabels WHERE objtype = $1 and objname = quote_literal($2) and provider = $3" 

I'm no go language developer to test it, but based on the chatgpt this should fix the issue

2024-10-17 08:28 UTC, stanleyz requested changes
@jbunting possible to update this and hopefully we can get this merged?

I am happy to help if you have other plans.

2024-10-17 08:28 UTC, stanleyz commented on postgresql/resource_postgresql_security_label.go
> +	query := "SELECT objtype, objname, provider, label FROM pg_seclabels WHERE objtype = $1 and objname = $2 and provider = $3"
As mentioned by other numbers, you need `quote_ident` on objname.

`SELECT objtype, objname, provider, label FROM pg_seclabels WHERE objtype = $1 and objname = quote_ident($2) and provider = $3`

2024-10-23 12:15 UTC, cyrilgdn commented
Closing in favor of #482 that supersedes it.

2024-10-23 12:15 UTC, closed without merging