Add postgresql_grant_role resource
cyrilgdn/terraform-provider-postgresql pull request #4
Opened 2020-11-22 23:17 UTC by dvdliao

Copying from https://github.com/hashicorp/terraform-provider-postgresql/pull/189

2020-11-27 08:23 UTC, cyrilgdn commented
@dvdliao Thanks for recreating it here, Hashicorp should have migrated the PRs & issues of the old repository but as it's still not the case we'll use this one.

I'll take a look this week-end. Could you just rebase on master?  I fixed the Travis build so it should pass now.

2020-11-30 19:24 UTC, dvdliao commented
@cyrilgdn done. thanks!

2020-12-12 16:07 UTC, cyrilgdn requested changes
Thanks a lot for your work on this :+1: , and really sorry for the response delay.

Could you just remove the `errwrap` dependency (cf comment)  and it's good for me.
(Other comments are not mandatory)

2020-12-12 16:07 UTC, cyrilgdn commented on postgresql/resource_postgresql_grant_role_test.go
> +	grantedRoleName := "foo"
This one could also be created with a `postgresql_role` in `testAccPostgresqlGrantRoleResources` directly so you don't have to create/destroy it yourself.

2020-12-14 01:00 UTC, dvdliao commented
@cyrilgdn done and thanks!

2020-12-14 13:35 UTC, cyrilgdn commented on postgresql/resource_postgresql_grant_role_test.go
>  				"with_admin_option": false,
This case is the same than the one above. You probably want to set it to true even it does not change the generated query.

2020-12-14 18:46 UTC, dvdliao commented
@cyrilgdn done

2020-12-21 09:56 UTC, cyrilgdn approved these changes
Thanks a lot :+1:

2020-12-21 09:56 UTC, merged

2020-12-21 18:34 UTC, dvdliao commented
hey @cyrilgdn any idea when a release will be cut? i see the milestone as completed https://github.com/cyrilgdn/terraform-provider-postgresql/milestone/2?closed=1

2020-12-21 20:24 UTC, cyrilgdn commented
@dvdliao  FYI, this has just been released in [v1.9.0](https://github.com/cyrilgdn/terraform-provider-postgresql/releases/tag/v1.9.0).